# Generated by Django 6.1.1 on 2026-09-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quality',
            new_name='quantity',
        ),
    ]
